#!/bin/sh

help () {
    echo "Usage: $0 <app_name> <remote_git_url> [<commit_or_tag>]"
}

appname="$1"
remote="$2"
commit="$3"

if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ -z "${appname}" ] || [ -z "${remote}" ]; then
    help
    exit 1
fi

container_name="build_${appname}_$(date +'%Y%m%d%H%M%S')"

docker run \
        -v "$(pwd)/sources:/root/sources:ro" \
        -v "$(pwd)/node_modules:/root/node_modules" \
        --name "${container_name}" dev-builder \
        /root/bin/build.sh "${appname}" "${remote}" "${commit}"

docker cp ${container_name}:/root/build .
