FROM debian

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y apt-transport-https

COPY jessie_backports.list /etc/apt/sources.list.d/jessie_backports.list

COPY nodesource.gpg /tmp/nodesource.gpg

RUN apt-key add /tmp/nodesource.gpg

COPY nodesource.list /etc/apt/sources.list.d/nodesource.list

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y \
        net-tools \
        bind9-host \
        vim \
        openssh-client \
        git \
        python \
        python-all \
        python-setuptools \
        python-dev \
        build-essential \
        devscripts \
        debhelper \
        lintian \
        virtualenv \
        nodejs
